config/urls.py
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path("", include("trips.urls")),
    path("accounts/", include("accounts.urls")),
]

if settings.DEBUG:
    from debug_toolbar.toolbar import debug_toolbar_urls
    urlpatterns += debug_toolbar_urls()

trips/urls.py
"""
URL configuration for the trips app.
"""

from django.urls import path
from . import views

app_name = "trips"
urlpatterns = [
    path("", views.index, name="index"),
    path("profile/", views.UserTripsView.as_view(), name="profile"),
    path("trip/new/", views.CreateTripView.as_view(), name="create-trip"),
    path("trip/<slug:slug>/", views.TripDetailView.as_view(), name="trip-detail"),
    path("trip/<slug:slug>/edit/", views.EditTripView.as_view(), name="edit-trip"),
    path("trip/<slug:slug>/delete/",
         views.DeleteTripView.as_view(), name="delete-trip"),
    path("destination/new/", views.CreateDestinationView.as_view(), name="create-dest"),
    path("trip/<slug:trip_slug>/destination/new/",
         views.CreateDestinationView.as_view(), name="create-dest-with-trip"),
    path("trip/<slug:trip_slug>/destination/<int:pk>/edit/",
         views.EditDestinationView.as_view(), name="edit-dest"),
    path("trip/<slug:trip_slug>/destination/<int:pk>/delete/",
         views.DeleteDestinationView.as_view(), name="delete-dest"),
    path("destination/loc-search/",
         views.SearchLocationView.as_view(), name="search-loc")
]

trips/models.py
"""
Models for the trips app.
"""

from nanoid import generate as generate_nanoid
from django.db import models
from django.conf import settings
from django.urls import reverse


def generate_random_slug():
    """Generates a 12 character nanoid"""
    return generate_nanoid(size=12)


class Trip(models.Model):
    """Representation of the trip table"""

    # primary key: id (auto set by django)
    slug = models.SlugField(default=generate_random_slug,
                            unique=True, editable=False)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    scheduled = models.BooleanField(default=False)
    notes = models.TextField(blank=True)

    def get_absolute_url(self):
        return reverse("trips:trip-detail", kwargs={"slug": self.slug})

    def __str__(self):
        return f'{self.title} ({self.slug})'


class Destination(models.Model):
    """Representation of the destination table"""
    # primary key: id (auto set by django)
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)
    start_time = models.DateTimeField(null=True, blank=True)
    end_time = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f'{self.name} [from Trip: {self.trip}]'

trips/forms.py
# accounts/forms.py
from django.forms import (ModelForm, ModelChoiceField, DateInput,
                          DateTimeInput, HiddenInput, CharField, TextInput)
from django.urls import reverse_lazy
from .models import Trip, Destination


class UIDateInput(DateInput):
    input_type = "date"


class UIDateTimeInput(DateTimeInput):
    input_type = "datetime-local"


class TripForm(ModelForm):
    class Meta:
        model = Trip
        fields = ("title", "start_date", "end_date", "scheduled", "notes")
        widgets = {
            "start_date": UIDateInput(),
            "end_date": UIDateInput(),
        }


class DestinationForm(ModelForm):
    trip = ModelChoiceField(queryset=Trip.objects, required=False,
                            empty_label="--- (Create a new trip for this destination) ---")

    location = CharField(required=False,
                         template_name="trips/location_search_field_snippet.html",
                         widget=TextInput(attrs={
                             "placeholder": "(Search for a new location)",
                             "hx-post": reverse_lazy("trips:search-loc"),
                             "hx-params": "location",
                             "hx-target": "next #id_location_results",
                             "hx-swap": "outerHTML",
                             "hx-trigger": "input delay:250ms",
                         }))

    class Meta:
        model = Destination
        fields = ("trip", "name", "location", "latitude",
                  "longitude", "start_time", "end_time")
        widgets = {
            "latitude": HiddenInput(),
            "longitude": HiddenInput(),
            "start_time": UIDateTimeInput(),
            "end_time": UIDateTimeInput(),
        }

    def __init__(self, *args, **kwargs):
        only_trip = kwargs.pop("only_trip", None)
        self.user = kwargs.pop("user", None)
        if not (only_trip or self.user):
            raise Exception(
                "DestinationForm requires either a user or a specific trip")
        super().__init__(*args, **kwargs)

        if only_trip:
            self.fields['trip'].queryset = Trip.objects.filter(pk=only_trip.pk)
            self.fields['trip'].initial = only_trip
            self.fields['trip'].disabled = True
        else:
            self.fields['trip'].queryset = Trip.objects.filter(owner=self.user)

    def clean_trip(self):
        if self.cleaned_data['trip']:
            return self.cleaned_data['trip']
        if self.user and self.data.get('name'):
            return Trip.objects.create(owner=self.user, title=self.data.get('name'))

trips/views.py
"""
Views for the trips app.
"""

import os
import requests
from http import HTTPStatus
from django.shortcuts import render, get_object_or_404
from django.views.generic import View, ListView, CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse, reverse_lazy
from django.http import HttpResponse, HttpResponseBadRequest
from django.db.models import Avg

from .models import Trip, Destination
from .forms import TripForm, DestinationForm


def index(request):
    """
    Render the app's homepage.
    """

    return render(request, "trips/index.html")


class UserTripsView(LoginRequiredMixin, ListView):
    """View for trips for a logged-in user."""
    context_object_name = "user_trip_list"
    template_name = "trips/profile.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["create_trip_form"] = TripForm()
        context["create_dest_form"] = DestinationForm(user=self.request.user)
        context["mapbox_api_key"] = os.getenv("MAPBOX_ACCESS_TOKEN")
        mapbox_trips = self.request.user.trip_set.annotate(avg_latitude=Avg('destination__latitude'), avg_longitude=Avg(
            'destination__longitude')).exclude(avg_latitude=None).exclude(avg_longitude=None)
        context["mapbox_trips"] = [{
            'title': trip.title,
            'avg_latitude': trip.avg_latitude,
            'avg_longitude': trip.avg_longitude,
            'link': trip.get_absolute_url(),
        } for trip in mapbox_trips]
        return context

    def get_queryset(self):
        return self.request.user.trip_set.all()


class TripDetailView(UserPassesTestMixin, DetailView):
    """View for single trip details."""
    model = Trip
    permission_denied_message = "You don't have access to this trip."

    def test_func(self):
        return self.request.user == self.get_object().owner

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["create_dest_form"] = DestinationForm(only_trip=self.object)
        mapbox_dests = self.object.destination_set.exclude(longitude=None).exclude(
            latitude=None).values('name', 'latitude', 'longitude')
        context["mapbox_destinations"] = list(mapbox_dests)
        context["mapbox_api_key"] = os.getenv("MAPBOX_ACCESS_TOKEN")
        return context


class CreateTripView(LoginRequiredMixin, CreateView):
    """View for creating a new trip."""

    template_name = "trips/create_trip.html"
    form_class = TripForm

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class EditTripView(UserPassesTestMixin, UpdateView):
    """View for updating a trip."""
    template_name_suffix = "_update_form"
    model = Trip
    form_class = TripForm
    permission_denied_message = "You don't have access to this trip."

    def test_func(self):
        return self.request.user == self.get_object().owner


class DeleteTripView(UserPassesTestMixin, DeleteView):
    """View for deleting a trip."""
    model = Trip
    success_url = reverse_lazy("trips:profile")
    permission_denied_message = "You don't have access to this trip."

    def test_func(self):
        return self.request.user == self.get_object().owner


class CreateDestinationView(UserPassesTestMixin, CreateView):
    """View for creating a new destination."""

    template_name = "trips/create_destination.html"
    form_class = DestinationForm
    permission_denied_message = "You don't have access to this trip."

    def setup(self, request, *args, **kwargs):
        self.trip = None
        trip_slug = kwargs.get("trip_slug")
        if trip_slug:
            self.trip = get_object_or_404(Trip, slug=trip_slug)

        return super().setup(request, *args, **kwargs)

    def test_func(self):
        if self.trip:
            return self.request.user == self.trip.owner
        return self.request.user.is_authenticated

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        if self.trip:
            kwargs["only_trip"] = self.trip
        kwargs["user"] = self.request.user
        return kwargs

    def get_success_url(self):
        return reverse("trips:trip-detail", args=[self.object.trip.slug])


class EditDestinationView(UserPassesTestMixin, UpdateView):
    """View for deleting a destination."""
    model = Destination
    form_class = DestinationForm
    template_name_suffix = "_update_form"
    permission_denied_message = "You don't have access to this trip."

    def setup(self, request, *args, **kwargs):
        trip_slug = kwargs.get("trip_slug")
        dest_pk = kwargs.get("pk")
        trip = get_object_or_404(Trip, slug=trip_slug)
        get_object_or_404(Destination, trip=trip, pk=dest_pk)

        return super().setup(request, *args, **kwargs)

    def test_func(self):
        return self.request.user == self.get_object().trip.owner

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def get_success_url(self):
        return reverse("trips:trip-detail", args=[self.object.trip.slug])


class DeleteDestinationView(UserPassesTestMixin, DeleteView):
    """View for deleting a destination."""
    model = Destination
    permission_denied_message = "You don't have access to this trip."

    def setup(self, request, *args, **kwargs):
        trip_slug = kwargs.get("trip_slug")
        dest_pk = kwargs.get("pk")
        trip = get_object_or_404(Trip, slug=trip_slug)
        get_object_or_404(Destination, trip=trip, pk=dest_pk)

        return super().setup(request, *args, **kwargs)

    def test_func(self):
        return self.request.user == self.get_object().trip.owner

    def get_success_url(self):
        return reverse("trips:trip-detail", args=[self.object.trip.slug])


class SearchLocationView(LoginRequiredMixin, View):
    """View for searching a location with Mapbox."""

    def post(self, request, *args, **kwargs):
        q = request.POST.get("location")
        if not q:
            return HttpResponseBadRequest("Missing search query")

        mapbox_access_token = os.environ["MAPBOX_ACCESS_TOKEN"]
        params = {
            "q": q,
            "access_token": mapbox_access_token,
            "auto_complete": "true",
        }
        response = requests.get(
            "https://api.mapbox.com/search/searchbox/v1/forward", params=params)

        if not response.ok:
            err = str({
                "reason": response.reason,
                "response": response.json()
            })
            return HttpResponse(err, status=HTTPStatus.BAD_GATEWAY)

        results = []
        for feature in response.json()["features"]:
            props = feature["properties"]
            coords = props["coordinates"]
            results.append({
                "name": props["name"],
                "place": props.get("place_formatted"),
                "latitude": coords["latitude"],
                "longitude": coords["longitude"],
            })

        return render(request, "trips/location_search_results_snippet.html", {"locations": results})

trips/templates/trips/create_destination.html
{% extends "base.html" %}
{% block subtitle %}
  New Destination
{% endblock subtitle %}
{% block content %}
  <h2>Create a new destination</h2>
  <form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Create Destination</button>
  </form>
{% endblock content %}

trips/templates/trips/create_trip.html
{% extends "base.html" %}
{% block subtitle %}
  New Trip
{% endblock subtitle %}
{% block content %}
  <h2>Create a new trip</h2>
  <form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Create Trip</button>
  </form>
{% endblock content %}

trips/templates/trips/destination_confirm_delete.html
{% extends "base.html" %}
{% block subtitle %}
  Delete Destination?
{% endblock subtitle %}
{% block content %}
  <form method="post">
    {% csrf_token %}
    <p>
      Are you sure you want to delete your destination <strong>{{ destination.name }}</strong>
      on trip <em>{{ destination.trip.title }}</em>?
    </p>
    {{ form }}
    <input type="submit" value="Confirm" />
  </form>
{% endblock content %}

trips/templates/trips/destination_update_form.html
{% extends "base.html" %}
{% block subtitle %}
  Edit Destination
{% endblock subtitle %}
{% block content %}
  <h2>Edit your destination</h2>
  <form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Save Destination</button>
  </form>
{% endblock content %}

trips/templates/trips/index.html
{% extends "base.html" %}
{% load static %}
{% block subtitle %}
  Travel Idea Tracker
{% endblock subtitle %}
{% block content %}
  <link rel="stylesheet" href="{% static "trips/index_styles.css" %}" />
  <h1 class="main-title">Wander&shy;lust</h1>
  <h2 class="main-subtitle">Your travel idea tracker</h2>
{% endblock content %}

trips/templates/trips/location_search_field_snippet.html
{% include "django/forms/field.html" %}
<div hidden id="{{ field.auto_id }}_results"></div>

trips/templates/trips/location_search_results_snippet.html
<div id="id_location_results">
  <script>
    function selectLocation(elem, event) {
      event.preventDefault();
      form = htmx.closest(elem, "form")

      latitudeInput = htmx.find(form, "input#id_latitude");
      latitudeInput.value = elem.dataset.latitude;

      longitudeInput = htmx.find(form, "input#id_longitude");
      longitudeInput.value = elem.dataset.longitude;

      locationSearchInput = htmx.find(form, "input#id_location");
      locationSearchInput.value = elem.textContent;

      // htmx.takeClass(htmx.closest(elem, "li"), "selected");
      htmx.swap(htmx.closest(elem, "div#id_location_results"), "", {swapStyle: 'innerHTML'});
    };
  </script>
  <ul>
    {% for location in locations %}
      <li>
        <button type="button"
                data-latitude="{{ location.latitude }}"
                data-longitude="{{ location.longitude }}"
                hx-on:click="selectLocation(this, event)">{{ location.name }} - {{ location.place }}</button>
      </li>
    {% endfor %}
  </ul>
</div>

trips/templates/trips/profile.html
{% extends "base.html" %}
{% block subtitle %}
  My Trips
{% endblock subtitle %}
{% block content %}
  <h2>My Trips</h2>
  {% if user_trip_list %}
    <div id="mapbox-map" style="width: 400px; height: 300px;"></div>
    <script>
        mapboxgl.accessToken = "{{ mapbox_api_key|safe }}";
        const map = new mapboxgl.Map({
          container: 'mapbox-map',
          style: 'mapbox://styles/mapbox/streets-v12',
        });
        const trips = {{ mapbox_trips|safe }};
        console.log(trips);
        trips.forEach((trip) => {
          const popup = new mapboxgl.Popup().setHTML(`<a href="${trip.link}">${trip.title}</a>`);
          const marker = new mapboxgl.Marker()
            .setLngLat([trip.avg_longitude, trip.avg_latitude])
            .setPopup(popup)
            .addTo(map);
        });
        const longs = trips.map(t=>t.avg_longitude)
        const lats = trips.map(t=>t.avg_latitude)
        const bounds = [Math.min(...longs), Math.min(...lats), Math.max(...longs), Math.max(...lats)]
        map.fitBounds(bounds, {padding: 50, maxZoom: 8});
    </script>
  {% endif %}
  <ul>
    {% for trip in user_trip_list %}
      <li>
        <a href="{% url "trips:trip-detail" trip.slug %}">{{ trip.title }}</a>
        {% if trip.start_date or trip.end_date %}
          [{{ trip.start_date|date|default:"(start)" }} - {{ trip.end_date|date|default:"(end)" }}]
        {% endif %}
      </li>
    {% empty %}
      <li>No trips for you ;_;</li>
    {% endfor %}
  </ul>
  <h3>Create a new trip</h3>
  <form action="{% url "trips:create-trip" %}" method="post">
    {% csrf_token %}
    {{ create_trip_form }}
    <button type="submit">Create New Trip</button>
  </form>
  <h3>Create a new destination</h3>
  <form action="{% url "trips:create-dest" %}" method="post">
    {% csrf_token %}
    {{ create_dest_form }}
    <button type="submit">Create Destination</button>
  </form>
{% endblock content %}

trips/templates/trips/trip_confirm_delete.html
{% extends "base.html" %}
{% block subtitle %}
  Delete Trip?
{% endblock subtitle %}
{% block content %}
  <form method="post">
    {% csrf_token %}
    <p>
      Are you sure you want to delete your trip <strong>{{ trip.title }}</strong>?
    </p>
    {{ form }}
    <input type="submit" value="Confirm" />
  </form>
{% endblock content %}

trips/templates/trips/trip_detail.html
{% extends "base.html" %}
{% block subtitle %}
  {{ trip.title }}
{% endblock subtitle %}
{% block content %}
  <h2>Trip - {{ trip.title }}</h2>
  <p>Owner: {{ trip.owner.username }}</p>
  <p>Start Date: {{ trip.start_date|date }}</p>
  <p>End Date: {{ trip.end_date|date }}</p>
  <p>
    Scheduled:
    {% if trip.scheduled %}
      Yes
    {% else %}
      No
    {% endif %}
  </p>
  <p>Notes: {{ trip.notes }}</p>
  <div>
    Destinations:
    {% if mapbox_destinations %}
      <div id="mapbox-map" style="width: 400px; height: 300px;"></div>
      <script>
        mapboxgl.accessToken = "{{ mapbox_api_key|safe }}";
        const map = new mapboxgl.Map({
          container: 'mapbox-map',
          style: 'mapbox://styles/mapbox/streets-v12',
        });
        const dests = {{ mapbox_destinations|safe }};
        console.log(dests);
        dests.forEach((dest) => {
          const popup = new mapboxgl.Popup().setText(dest.name);
          const marker = new mapboxgl.Marker()
            .setLngLat([dest.longitude, dest.latitude])
            .setPopup(popup)
            .addTo(map);
        });
        const longs = dests.map(d=>d.longitude)
        const lats = dests.map(d=>d.latitude)
        const bounds = [Math.min(...longs), Math.min(...lats), Math.max(...longs), Math.max(...lats)]
        map.fitBounds(bounds, {padding: 50, maxZoom: 15});
      </script>
    {% endif %}
    <ul>
      {% for dest in trip.destination_set.all %}
        <li>
          <div>{{ dest.name }}</div>
          {% if dest.start_time %}<div>Starts at: {{ dest.start_time }}</div>{% endif %}
          {% if dest.end_time %}<div>Ends at: {{ dest.end_time }}</div>{% endif %}
          <div>
            <a href="{% url "trips:edit-dest" trip.slug dest.pk %}">Edit this destination</a>
          </div>
          <div>
            <a href="{% url "trips:delete-dest" trip.slug dest.pk %}">Delete this destination</a>
          </div>
        </li>
      {% endfor %}
    </ul>
    <h3>Create a new destination</h3>
    <form action="{% url "trips:create-dest-with-trip" trip.slug %}"
          method="post">
      {% csrf_token %}
      {{ create_dest_form }}
      <button type="submit">Create Destination</button>
    </form>
  </div>
  <p>
    <a href="{% url "trips:edit-trip" trip.slug %}">Edit this trip</a>
  </p>
  <p>
    <a href="{% url "trips:delete-trip" trip.slug %}">Delete this trip</a>
  </p>
{% endblock content %}

trips/templates/trips/trip_update_form.html
{% extends "base.html" %}
{% block subtitle %}
  Edit Trip
{% endblock subtitle %}
{% block content %}
  <h2>Edit your trip</h2>
  <form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Save Trip</button>
  </form>
{% endblock content %}