accounts/urls.py
"""
URL configuration for the accounts app.
"""

from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views

app_name = "accounts"
urlpatterns = [
    path("password_change/", auth_views.PasswordChangeView.as_view(
        success_url=reverse_lazy("accounts:password_change_done"))),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("settings/", views.AccountView.as_view(), name="settings"),
    path("edit/", views.EditAccountView.as_view(), name="edit"),
    path("delete/", views.DeleteAccountView.as_view(), name="delete"),
    path("", include("django.contrib.auth.urls")),
]

config/urls.py
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path("", include("trips.urls")),
    path("accounts/", include("accounts.urls")),
]

if settings.DEBUG:
    from debug_toolbar.toolbar import debug_toolbar_urls
    urlpatterns += debug_toolbar_urls()

trips/urls.py
"""
URL configuration for the trips app.
"""

from django.urls import path
from . import views

app_name = "trips"
urlpatterns = [
    path("", views.index, name="index"),
    path("profile/", views.UserTripsView.as_view(), name="profile"),
    path("trip/new/", views.CreateTripView.as_view(), name="create-trip"),
    path("trip/<slug:slug>/", views.TripDetailView.as_view(), name="trip-detail"),
    path("trip/<slug:slug>/edit/", views.EditTripView.as_view(), name="edit-trip"),
    path("trip/<slug:slug>/delete/",
         views.DeleteTripView.as_view(), name="delete-trip"),
    path("destination/new/", views.CreateDestinationView.as_view(), name="create-dest"),
    path("trip/<slug:trip_slug>/destination/new/",
         views.CreateDestinationView.as_view(), name="create-dest-with-trip"),
    path("trip/<slug:trip_slug>/destination/<int:pk>/edit/",
         views.EditDestinationView.as_view(), name="edit-dest"),
    path("trip/<slug:trip_slug>/destination/<int:pk>/delete/",
         views.DeleteDestinationView.as_view(), name="delete-dest"),
    path("destination/loc-search/",
         views.SearchLocationView.as_view(), name="search-loc")
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="keywords" content="travel" />
    <meta name="description"
          content="Keep track of the travelling you want to do." />
    <title>Wanderlust -
      {% block subtitle %}
      {% endblock subtitle %}
    </title>
    <link rel="stylesheet" href="{% static "base_styles.css" %}" />
    <script src="https://unpkg.com/htmx.org@2.0.4"
            integrity="sha384-HGfztofotfshcF7+8n44JQL2oJmowVChPTg48S+jvZoztPfvwD79OC/LTtG6dMp+"
            crossorigin="anonymous"></script>
    <script src='https://api.mapbox.com/mapbox-gl-js/v3.11.0/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v3.11.0/mapbox-gl.css'
          rel='stylesheet' />
  </head>
  <body>
    <header class="base">
      <div class="icon">
        <a href={% url "trips:index" %}>
          <img src="https://placehold.co/400"
               alt="homepage icon"
               height="50px"
               width="50px" />
        </a>
      </div>
      <nav>
        <ul>
          {% if user.is_authenticated %}
            <li>
              <a href="{% url "trips:profile" %}">My Trips</a>
            </li>
            <li>
              <a href="{% url "accounts:settings" %}">Settings</a>
            </li>
            <li>
              <form action="{% url "accounts:logout" %}" method="post">
                {% csrf_token %}
                <button type="submit">Log Out</button>
              </form>
            </li>
          {% else %}
            <li>
              <a href="{% url "accounts:login" %}">Log In</a>
            </li>
            <li>
              <a href="{% url "accounts:signup" %}">Sign Up</a>
            </li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main>
      {% block content %}
      {% endblock content %}
    </main>
    <footer>
      Created by <a href="https://kiko.codes">Kiko Otutuloro</a> © 2025
    </footer>
  </body>
</html>

templates/base_error.html
{% extends "base.html" %}
{% block subtitle %}
  Error
{% endblock subtitle %}
{% block content %}
  <h1>
    Oopsies:
    {% block error_code %}
    {% endblock error_code %}
  </h1>
  <h2>
    {% block error_message %}
    {% endblock error_message %}
  </h2>
{% endblock content %}

templates/error-base.html
{% extends "base.html" %}
{% block subtitle %}
  Error
{% endblock subtitle %}
{% block content %}
  <h1>
    Oopsies:
    {% block error_code %}
    {% endblock error_code %}
  </h1>
  <h2>
    {% block error_message %}
    {% endblock error_message %}
  </h2>
{% endblock content %}